version: '3.7'
services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 8080:80
    container_name: web
    networks:
      - test
  test:
    build:
      context: test/
      dockerfile: Dockerfile
      no_cache: true
    container_name: test
    depends_on:
      - web
    volumes:
      - ./test:/app/
      - /app/node_modules/
    security_opt:
      - seccomp:./test/chrome.json
    stdin_open: true
    tty: true
    networks:
      - test
networks:
  test: