name: CI

on:
  push:
    # All branches
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        sudo chmod 666 /var/run/docker.sock

    - name: Start Docker Compose
      run: docker-compose up -d --build -V --quiet-pull 
    
    - name: Check if the application is running
      run: |
        #!/bin/bash
        set -e
        # Check if the test application is running, if it doesn't, exit the github actions with an error
        if ! [ "$(docker-compose ps -q test)" ]; then
          echo "Application is not running"
          exit 1
        fi
      
#    - name: Copy test results screenshots to host machine
#      run: docker cp -r test:/app/screenshots .
    # the test results are in the test container, so we need to copy them to the host machine first
    - 
      name: Wait for the test to finish
      run: |
        #!/bin/bash
        sleep 10
    - name: Extract the screenshots folder to the host machine
      run: |
          docker cp test:/app/screenshots .
          ls -al screenshots/
    - name: Extract the test results to the host machine
      run: docker cp test:/app/documentation.md .
    - name: Stop Docker Compose
      run: docker-compose down
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: test/screenshots
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test/documenation.md