name: CI

on:
  push:
    # All branches
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        sudo chmod 666 /var/run/docker.sock

    - name: Start Docker Compose
      run: docker-compose up -d --build -V

    - name: Wait for application to start
      run: sleep 10
    
    - name: Run tests
      run: |
        #!/bin/bash
        set -e
        # Check if screenshots exists and it's not empty, and it has 3 subdirectories (moblie, tablet, desktop) in the test container, if it doesn't, exit the github actions with an error
        if ! [ "$(docker-compose exec test ls -A /app/test/screenshots)" ] || [ "$(docker-compose exec test ls -A /app/test/screenshots | wc -l)" -ne 3 ]; then
          echo "Screenshots directory does not exist or is empty"
          exit 1
        fi
        # Check if the documentation.md file exists in the test container, if it doesn't, exit the github actions with an error
        if ! [ "$(docker exec -it test ls -A /app/test/documentation.md)" ]; then
          echo "Documentation file does not exist"
          exit 1
        fi

    - name: Stop Docker Compose
      run: docker-compose down
    
    # the test results are in the test container, so we need to copy them to the host machine first
    - name: Copy test results to host machine
      run: docker cp test:/app/test/documentation.md .
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: documentation.md
    