name: CI

on:
  push:
    # All branches
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        sudo chmod 666 /var/run/docker.sock

    - name: Start Docker Compose
      run: docker-compose up -d --build -V --quiet-pull 
    
    - name: Check if the application is running
      run: |
        #!/bin/bash
        set -e
        # Check if the test application is running, if it doesn't, exit the github actions with an error
        if ! [ "$(docker-compose ps -q test)" ]; then
          echo "Application is not running"
          exit 1
        fi
#    - name: Copy test results screenshots to host machine
#      run: docker cp -r test:/app/screenshots .
    # the test results are in the test container, so we need to copy them to the host machine first
    - name: Set up Node.js with NVM
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the desired Node.js version

    - name: Install dependencies
      run: |
        cd test
        npm install

    - name: Run tests
      run: |
        cd test
        npm start
    - name: Stop Docker Compose
      run: docker-compose down
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: test/screenshots
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test/documenation.md